CREATE TABLE `bd_bu_price`  (
  `CREATED_BY` bigint(20) NOT NULL COMMENT '创建人',
  `CREATION_DATE` datetime(0) NOT NULL COMMENT '创建时间',
  `LAST_UPDATED_BY` bigint(20) NOT NULL COMMENT '最后更新人',
  `LAST_UPDATE_DATE` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '最后更新时间',
  `LAST_UPDATE_LOGIN` bigint(20) NOT NULL COMMENT '最后更新时登录ID',
  `CID` bigint(20) NOT NULL DEFAULT 1,
  `TENANT_ID` bigint(20) NOT NULL COMMENT '关联SYS_TENANT表中的TENANT_ID',
`ITEM_ID` bigint(20) COMMENT '物料ID',
`BASE_PRICE` decimal(10,6) COMMENT '单价',
`PRICING_UOM_CODE` varchar(10) CHARACTER SET utf8 COLLATE utf8_bin  COMMENT '定价单位',
`CURRENCY_CODE` varchar(10) CHARACTER SET utf8 COLLATE utf8_bin  COMMENT '币种',
`FROM_BU_CODE` varchar(60) CHARACTER SET utf8 COLLATE utf8_bin  COMMENT '发出业务单元',
`TO_BU_CODE` varchar(60) CHARACTER SET utf8 COLLATE utf8_bin  COMMENT '接收业务单元',
`CHARGE_START_DATE` datetime(0) COMMENT '价格生效日期',
`CHARGE_LAST_UPDATE_DATE` datetime(0) COMMENT '价格失效日期'
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '公司间交易价目表' ROW_FORMAT = Dynamic;